
// 控制加号的大小
export const ADD_WIDTH = "48vp"
export const ADD_HEIGHT = "48vp"

// 控制加号的相对位置
export const ADD_POSITION_X = "80%"
export const ADD_POSITION_Y = "90%"

export const ADD_DIALOG_DIVIDER_COLOR = "#fff1efef"
export const ADD_DIALOG_MARGIN = "12vp"
export const ADD_DIALOG_AMOUNT_PLACEHOLDER = "请输入金额..."
export const ADD_DIALOG_DETAIL_PLACEHOLDER = "请输入详细信息..."
export const ADD_DIALOG_CONFIRM_FONT_SIZE = "16fp"
export const ADD_DIALOG_CONFIRM_HEIGHT = "40vp"
export const ADD_DIALOG_CONFIRM_TEXT = "添加"
export const ADD_DIALOG_HINT1 = "账目类型不能为空"
export const ADD_DIALOG_HINT2 = "账目金额不为合理"