

export const GROUP_BACKGROUND = Color.White
export const GROUP_HEAD_BACKGROUND = "#ffeeeeee"
export const GROUP_HEAD_FONT_SIZE = "13fp"
export const GROUP_END_WIDTH = "30vp"
export const GROUP_DIVIDER_START = "54vp"
export const GROUP_DIVIDER_END = "0vp"
export const GROUP_BORDER_RADIUS = "20vp"
export const GROUP_MARGIN_BOTTOM = "12vp"
export const GROUP_PADDING = "5vp"

export const SIGNAL_IMAGE_WIDTH = "30vp"
export const SIGNAL_IMAGE_MARGIN = "15vp"
export const SIGNAL_CATEGORY_TEXT_FONT_SIZE = "16fp"
export const SIGNAL_CATEGORY_TEXT_FONT_COLOR = "#FF182431"

export const SIGNAL_DETAIL_TEXT_FONT_SIZE = "14fp"
export const SIGNAL_DETAIL_TEXT_FONT_COLOR = "#99182431"
export const SIGNAL_DETAIL_TEXT_MARGIN_TOP = "5vp"

export const SIGNAL_AMOUNT_FONT_SIZE = "14fp"
export const SIGNAL_AMOUNT_MARGIN_RIGHT = "4vp"
export const SIGNAL_AMOUNT_FONT_COLOR_PAY = Color.Black
export const SIGNAL_AMOUNT_FONT_COLOR_EARN = "#e9f8c03e"